fixx

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,6 +37,10 @@ jobs:
         run: ls -la
       - name: List build directory contents
         run: ls -la build || echo "Build directory not found"
+      - name: List build/_app directory contents
+        run: ls -la build/_app || echo "Build/_app directory not found"
+      - name: List build/_app/immutable directory contents
+        run: ls -la build/_app/immutable || echo "Build/_app/immutable directory not found"
       - name: Create .nojekyll file
         run: touch build/.nojekyll
       - name: Setup Pages
